---
galaxy_info:
  author: Denis Ryabyy <vv1r0x@gmail.com>, Denis a.k.a Difrex Zheleztsov <difrex.punk@gmail.com>
  description: Ansible role for installing docker for Debian.
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
    - system
dependencies:
